# Regular configuration parameters

runId: ~          # Empty runId - will be set automatically
dataset: 1KGP
chromosome: 22
segLen: -1
overlap: 0
population: ALL

# Auxiliary for training
model: scda
bioAware: False
useWandB: True
batchSize: 1024
dropoutRate: 0.0
learningRate: ~  # Empty - will be filled by grid search
loss: focalLoss
sampling: normal
upsamplingRatio: 0.8
totalEpochs: 1400
warmupEpochs: 10
scheduler: cosineAnn
adamwBeta1: 0.9
adamwBeta2: 0.99
adamwEps: 0.00000001
adamwWeightDecay: 0.05
seed: 1024
missingRatio: 0.25
dynamicRatio: False
bertStrategy: False

# Auxiliary for testing/benchmarking
benchmarkAll: True
batchSizeTest: 512
epoch: 0

# SLURM settings
slurm_settings:
  partition: gpu2
  nodes: 3
  ntasks: 6
  ntasks-per-node: 2
  gpus-per-task: 1
  gres: gpu:2

# Grid search configuration (will be removed from final configs)
grid_search:
  run_id_prefix: LONI_Mar04
  params:
    learningRate:
      - 0.0021
      - 0.0037
      - 0.0054
      - 0.0061
