runId: ~

dataset: HLA
chromosome: 6
population: ALL
segLen: 128
overlap: 64
unique: False

model: unet
batchSize: 64
dropoutRate: 0.0
learningRate: ~
scheduler: cosineAnn
loss: hybridFocalLoss
dosageLossLambda: 0.65 # 0.8 MSE will be more important, 0.65 will be balanced since CE loss is roughly twice as the MSE loss
sampling: normal
upsamplingRatio: 0.8
finetuning: False
targetBin: 0.001-0.005
totalEpochs: 1600
warmupEpochs: 10
cooldownEpochs: 0
adamwBeta1: 0.9
adamwBeta2: 0.99
adamwEps: 0.00000001
adamwWeightDecay: 0.01
seed: 42
missingRatio: 0.9
dynamicRatio: False

#modelDir: archive/exp1/HLA_chr6_ALL_seg128_overlap64/checkpoints
#analysisDir: archive/exp1/HLA_chr6_ALL_seg128_overlap64/analysis
benchmarkAll: True
batchSizeTest: 1024
epoch: 0

# SLURM settings
slurm_settings:
  partition: gpu2
  nodes: 3
  ntasks: 6
  ntasks-per-node: 2
  gpus-per-task: 1
  gres: gpu:2

# Grid search configuration (will be removed from final configs)
grid_search:
  run_id_prefix: LONI_Mar10
  params:
    learningRate:
      - 0.0018
      - 0.0027
      - 0.0032
      - 0.0041
