runId: manuscript_v2
dataset: 1KGP
chromosome: 22
segLen: 1024
overlap: 128
population: ALL
model: unet
bioAware: True
depth: 6
nchannels: 48
kernelSize: 7
stride: 1
dropoutRate: 0.05
useGroupNorm: True
gnGroups: 8
batchSize: 256
batchSizeTest: 8
learningRate: 0.0008
loss: hybridWeightedFocalLoss
dosageLossLambda: 0.5
focalAlpha: 0.25
focalGamma: 2.0
sampling: normal
useWandB: False
finetuning: False
totalEpochs: 700
warmupEpochs: 10
scheduler: cosineAnn
adamwBeta1: 0.9
adamwBeta2: 0.99
adamwEps: 0.00000001
adamwWeightDecay: 0.01
seed: 42
missingRatio: 0.95
dynamicRatio: True
bertStrategy: False
benchmarkAll: True
perVariantR2: True
epoch: 670
bins: [0.0, 0.005, 0.01, 0.05, 0.40, 0.5]
missing: [0.95]
testRandStates: [42]
