runId: v3_low_seg128
dataset: LOS
chromosome: 22
chromosomes: [22]
segLen: 128
overlap: 16
population: ALL
model: unet
bioAware: True
depth: 6
nchannels: 48
kernelSize: 7
stride: 1
dropoutRate: 0.05
useGroupNorm: False
batchSize: 256
batchSizeTest: 8
learningRate: 0.0005
loss: hybridWeightedFocalLoss
dosageLossLambda: 0.5
focalAlpha: 0.25
focalGamma: 2.0
sampling: normal
useWandB: False
finetuning: False
totalEpochs: 700
warmupEpochs: 10
scheduler: cosineAnn
adamwBeta1: 0.9
adamwBeta2: 0.99
adamwEps: 0.00000001
adamwWeightDecay: 0.01
seed: 42
missingRatio: 0.95
dynamicRatio: True
bertStrategy: False
benchmarkAll: True
perVariantR2: True
epoch: 210
bins: [0.001, 0.005, 0.010, 0.100, 0.200, 0.300, 0.400, 0.500]
missing: [0.05]
testRandStates: [42]
