# BiU-Net on the HLA region of chromosome 6 of the Simons Genome Diversity Project.
runId: exp1
dataset: HLA
chromosome: 6
chromosomes: [6]
segLen: 128
overlap: 64
population: ALL
model: unet
bioAware: True
depth: 6
nchannels: 32
kernelSize: 7
stride: 1
dropoutRate: 0.0
useGroupNorm: False
batchSize: 64
batchSizeTest: 1024
learningRate: 0.0018
loss: hybridWeightedFocalLoss
dosageLossLambda: 0.5
sampling: normal
upsamplingRatio: 0.8
useWandB: False
finetuning: False
totalEpochs: 3000
warmupEpochs: 10
scheduler: cosineAnn
adamwBeta1: 0.9
adamwBeta2: 0.99
adamwEps: 0.00000001
adamwWeightDecay: 0.01
seed: 42
missingRatio: 0.5
dynamicRatio: False
bertStrategy: False
benchmarkAll: True
bins: [0.001, 0.005, 0.010, 0.100, 0.200, 0.300, 0.400, 0.500]
missing: [0.05, 0.15, 0.25]
testRandStates: [0, 42, 1024]
epoch: 0
